### ISSUE TITLE
How can I learn this layout by heart?

### ISSUE THREAD

**Issue by mongrelion** [workman-layout/Workman#11]
I learnt the qwery layout back in primary school and I remember some exercises that the teacher would give us. Now I was trying to do the same thing with this layout (which so far with a couple of test paragraphs I could see how really productive and efficient it can be) but I'm not really sure that that's the way to go.
Is there any kind of guide that I could follow in order to learn and master the Workman layout?
Thanks in advance.

**Comment by rasisin** [comment]
Right: 

- Practice for hours and hours using any online typing software. 
- Focus on learning each letter very well before trying a new one. No more than 4 new letters per day.
- When you're not at a computer and have free time, practice in your head. Look at words around you (or think of words) and imagine typing them.

- DO NOT use any other keyboard if you can help it. If there's work you need to do on a computer, do your input by handwriting on a tablet until you learn Workman well enough to use it for work.

**Comment by BartlomiejSkwira** [comment]
The page http://www.workmanlayout.com is not working but archive.org has it saved https://web.archive.org/web/20160915170450/http://www.workmanlayout.com/blog/?p=752 Take a look in the "Recent Posts" section below the blog entry, there are multiple other ways to learn Workman listed.

**Comment by rasisin** [comment]
The Workman layout site has been revived at [http://workmanlayout.org/](http://workmanlayout.org/)), though it does not include the blog.
I learned Workman using [https://www.keybr.com/](https://www.keybr.com/), so I can verify that particular site's effectiveness.

**Comment by AstolfoKawaii** [comment]
typingstudy.com [supports](https://www.typingstudy.com/en-us_workman-3/lesson/1) workman
