### ISSUE TITLE
Android Support?

### ISSUE THREAD

**Issue by gooddadmike** [workman-layout/Workman#26]
I couldn't find it anywhere. Is it available? If so can you link to it. if not can you make it/get someone to make it?

**Comment by joel0** [comment]
I don't think Gboard supports custom layouts.  Is there a third party keyboard that supports custom layout that you want the Workman layout for?

**Comment by gooddadmike** [comment]
I think the routes to this existing in Android are 

- The hardest/best option would be to propose Workman as a standard like Dvorak so that it can be found in the language options
- You could create a stand alone keyboard app
- You could submit your layout as an option to popular 3rd party keyboards like [swype](https://play.google.com/store/apps/details?id=com.nuance.swype.dtc&hl=en) or [swiftkey](https://play.google.com/store/apps/details?id=com.touchtype.swiftkey) or [Fleksy](https://play.google.com/store/apps/details?id=com.syntellia.fleksy.keyboard) or [hackers keyboard](https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard&hl=en)

**Comment by Wisdawn** [comment]
Hi. I'm not sure if I'm missing something but I cannot find the Workman layout in the Input Languages list after installing, enabling, and selecting Hacker's Keyboard on my Anroid 6.0.1 phone. I wasn't even aware of the existence of Workman on Android until now. Any info or putting me in the right direction would be greatly appreciated.

**Comment by ajgrf** [comment]
My pull request to add Workman to [AnySoftKeyboard](https://github.com/AnySoftKeyboard/AnySoftKeyboard) was just accepted. It should be included in the next release, although I don't know when that will be.

**Comment by HaoZeke** [comment]
You could also setup a custom layout with the [https://play.google.com/store/apps/details?id=kl.ime.oh](Multiling O Keyboard).

**Comment by ajgrf** [comment]
[AnySoftKeyboard](https://github.com/AnySoftKeyboard/AnySoftKeyboard) just released a new version, and it now supports the Workman layout.

**Comment by Wisdawn** [comment]
@ajgrf Thank you so much for letting us know, Alex! This is awesome news for me.

**Comment by Wisdawn** [comment]
@ajgrf Almost forgot, and thank you so much for your work on it to give AnySoftKeyboard an easier task.

@HaoZeke Thank you for the alternative solution. Hopefully, I won't need to do that now, but I'll remember what you said should I not be happy with AnySoftKeyboard for some reason in the future.

**Comment by doamatto** [comment]
Since this was resolved, we can both close this issue and possibly make a PR to document where you can use Workman on Android

**Comment by gooddadmike** [comment]
agreed. Was this ever added to documentation?
