### ISSUE TITLE
People

### ISSUE THREAD

**Issue by sooqua** [workman-layout/Workman#33]
Typing "people" on this layout is very awkward. Back to Dvorak.

**Comment by sooqua** [comment]
As well as all the other words with the "op" bigram.

**Comment by macie** [comment]
This layout was created to solve some issues of other known layouts (_Dvorak_ too). You can find details at https://workmanlayout.org/ 

(@kdeloach this issue can be closed)

**Comment by yg8ijvjvjv** [comment]
Because Workman relies on OP same finger and relies on PO same finger.
