### ISSUE TITLE
WorkmanLayout.com is Down

### ISSUE THREAD

**Issue by AlexIljin** [workman-layout/Workman#34]
Hello!

The http://www.workmanlayout.com seems to have been blocked since November of 2016. The root redirects to http://www.workmanlayout.com/cgi-sys/suspendedpage.cgi, and the page says:

```
The website you were trying to reach is temporarily unavailable.
Please check back soon.
If you are the owner of this website, please contact Technical Support as soon as possible.
```

**Comment by rasisin** [comment]
Yes, it was moved to http://workmanlayout.org/

**Comment by AlexIljin** [comment]
Interesting... Why not update the link in the project description at https://github.com/ojbucao/Workman and in the Readme file?

**Comment by rasisin** [comment]
Bucao has lost interest in Workman. The new web site was set up by members of the community, as discussed here:
(https://github.com/ojbucao/Workman/issues/31)
I don't know if any of them have privileges to update the project description here. But you're right that it needs to be done.

**Comment by BartlomiejSkwira** [comment]
Well this repo looks like abandonware. I'd would go with a total ownership transfer https://help.github.com/articles/about-repository-transfers/ . @ojbucao - can you transfer the project to @kdeloach ? this way we would have only 1 main repo.

**Comment by kdeloach** [comment]
@ryenus suggested creating a new organization for the Workman layout, which I think is a great idea.

See: https://github.com/kdeloach/workman/issues/9

**Comment by macie** [comment]
@kdeloach I think that new organization repo and .org website fix this issue.

**Comment by joel0** [comment]
Can this issue be closed?  It appears that GoDaddy will auction off `workmanlayout.com` for a minimum bid of $2,500, so I doubt this project will get it back unfortunately.  The `workmanlayout.org` domain shows up at the top of search results, so I think this issue has effectively been resolved.

**Comment by AlexIljin** [comment]
Closing the issue, since the old repository now redirects to the community repository, which has the correct link in the Readme file.
