### ISSUE TITLE
Download link from official site

### ISSUE THREAD

**Issue by macie** [workman-layout/Workman#41]
https://workmanlayout.org/ has link to download compressed file from kdeloach fork (which is behind workman master branch). It should be link to this repo.

It is probably resolved by #39

**Comment by joel0** [comment]
It looks like this has been resolved, probably by https://github.com/kdeloach/workman/pull/11 .

#39 will also update the images to link to this repo, which are currently still pointing at @kdeloach 's repo.

You can probably close this issue.

**Comment by macie** [comment]
Yes, it resolves the problem. Thanks!
