### ISSUE TITLE
Any plans for multilingual support?

### ISSUE THREAD

**Issue by vhanla** [workman-layout/Workman#43]
On other languages there are special symbols, and Colemak does a great job there
https://colemak.com/Multilingual is a good starting point. 

Is there any possibility to include in Workman?

**Comment by letarg0** [comment]
klawiatura.wordpress.com this are multilanguage, 3 modificator, more keys, 2 potenciometer
no print screen, scroll lock and pause
;)

**Comment by vhanla** [comment]
The issue here, keyboard usage has to be done with few finger movements, and without even watching it. With that layout you have to be watching an moving your hands/fingers for the new buttons. I'm not fan of more keys. I just modified using microsoft's tool to edit custom keyboard layouts. Thank you anyway.

**Comment by letarg0** [comment]
You are not fan more keys because Your alphabet have small set
