### ISSUE TITLE
Can I release my Windows10 implementation of the Bulgarian Workman Layout?

### ISSUE THREAD

**Issue by PSStefanov19** [workman-layout/Workman#67]
[REQUEST]I have created a Bulgarian Workman Layout for Windows but I am unsure if I can release it to the public or if I have to keep it in a private repository. The layout is Phonetic Traditional.

**Comment by juk4iuugmov** [comment]
You have made this Bulgarian/Workman layout and Workman is open-source, so I don't think that you need to keep it private.

**Comment by joel0** [comment]
I'll refer you to the [license](https://github.com/workman-layout/Workman/blob/master/LICENSE); specifically "You may however make variations of the Workman Layout that does not modify or change the alphabetic arrangement of the original and you may call it as some variation of the Workman Layout (e.g. Workman Layout wide mod, etc.)"

Without seeing your layout, I can't say for sure whether your layout covered by that, but it sounds like it is.
