### ISSUE TITLE
Ubuntu PPA

### ISSUE THREAD

**Issue by PanderMusubi** [workman-layout/Workman#9]
Could you please offer a packages via an Ubuntu PPA on Launchpad to install what is needed on Ubuntu via apt-get?

**Comment by joel0** [comment]
Is an apt package still necessary?  It appears that every currently supported version of mainstream Ubuntu (19.10, 18.04, 16.04, and 14.04 desktop and server) all have Workman bundled in.

**Comment by PanderMusubi** [comment]
Then not. If you want you can close this issue according to me.

**Comment by joel0** [comment]
I'm not on the organisation on GitHub or a "collaborator" on this project, so I can't close the issue myself.

If you agree with my assessment that an apt package is no longer needed, I suggest you close this issue. But if I overlooked a reason why the package could still be desired, please do explain so someone can implement it.

Thank you.
